### ISSUE TITLE
missing "open_manipulator_motion/MotionState.h"

### ISSUE THREAD

**Issue by cybernetchi** [zang09/open_manipulator_6dof_application#2]
Hi @zang09 when I catkin_make the following:
open_manipulator_friends.git
open_manipulator_6dof_simulations.git
open_manipulator_6dof_application.git

I got the compile error:

```
fatal error: open_manipulator_motion/MotionState.h: No such file or directory
   52 | #include "open_manipulator_motion/MotionState.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

Can you please give me some help?
Thank you very much

**Comment by zang09** [comment]
Hi @cybernetchi, you have to build this package first or try `catkin_make` more time.
This compile error occur because message_generator cannot make header file in `catkin_ws/devel` folder. 
Thank you.
